### ISSUE TITLE
Setting crop color

### ISSUE THREAD

**Issue by ndgreen** [lvillani/android-cropimage#32]
Is there a way to change the crop line color (for example the pink line for the circle crop to a different color)

**Comment by lvillani** [comment]
I guess it's possible but I'll have to look into it. I'm taking a note to give it a look between today and tomorrow.

**Comment by lvillani** [comment]
Looks like the color is hard-coded within `HighlightView.java`:

* https://github.com/lvillani/android-cropimage/blob/e3efea734f8b5d5afa3a88b885592cab208d5983/CropImage/src/main/java/com/android/camera/HighlightView.java#L96
* https://github.com/lvillani/android-cropimage/blob/e3efea734f8b5d5afa3a88b885592cab208d5983/CropImage/src/main/java/com/android/camera/HighlightView.java#L99

I'll have to work on a patch to make it configurable.

**Comment by ndgreen** [comment]
Looks like that is the spot. It would be nice to have a patch to change it dynamically in the java code. Thanks, the code is working great

**Comment by lvillani** [comment]
The code is from Google, I just repackaged it in a library :wink: 

Anyway, the plan is to add a couple of Intent extras recognised by the CropImage activity. I just need to reserve one hour to work on this but I'm pretty busy right now.
