### ISSUE TITLE
Set initial crop region

### ISSUE THREAD

**Issue by imackinn** [lvillani/android-cropimage#33]
![screen shot 2015-02-14 at 6 29 49 pm](https://cloud.githubusercontent.com/assets/492889/6201885/f6d50be8-b477-11e4-9386-cd18aa17d6e4.png)

Is there a way to have the highlighted region extend to at least one of the edges of the selected image? Right now if a user wants to crop just one dimension they have to drag first.

**Comment by lvillani** [comment]
I don't think it's possible as-is. The default is to always leave some margin around the edges as long as the picture is zoomed and the rectangle doesn't encompass the whole picture in one direction.
