### ISSUE TITLE
Is it possible to change crop ratio?

### ISSUE THREAD

**Issue by drabelo** [lvillani/android-cropimage#37]
Is it possible to change the crop ratio from 1:1? I changed the output X and Y but it still doesn't change the ratio while selecting.

**Comment by lvillani** [comment]
Yes, see [here](https://github.com/lvillani/android-cropimage/blob/3916ed9f87d000379d066d24788f7727941db86c/CropImage/src/main/java/com/android/camera/CropImageIntentBuilder.java#L91-L94)
