### ISSUE TITLE
setOutlineColor not found

### ISSUE THREAD

**Issue by BatDroid** [lvillani/android-cropimage#38]
in example code :
https://github.com/lvillani/android-cropimage/blob/master/CropImageExample/src/main/java/com/android/camera/example/MainActivity.java

in line of 63 the method setOutlineColor is missing.
i would appreciate if you can help me please to change the outline Color.

**Comment by lvillani** [comment]
I'm not sure I understand your question: the example compiles and runs fine for me.

**Comment by lvillani** [comment]
I'm not sure I understand your question: the example compiles and runs fine for me. Can you provide more details?

**Comment by BatDroid** [comment]
there is no "setoutlineColor" method in library to be called.
by the way i know its irrelevant to issue subject but is it possible to get the library from a repsitory for api >=14?

**Comment by lvillani** [comment]
> there is no "setoutlineColor" method in library to be called.

The function is defined right [here](https://github.com/lvillani/android-cropimage/blob/3916ed9f87d000379d066d24788f7727941db86c/CropImage/src/main/java/com/android/camera/CropImageIntentBuilder.java#L278). I'm not sure why you are getting this problem though.

> by the way i know its irrelevant to issue subject but is it possible to get the library from a repsitory for api >=14?

There is already a repository, see the relevant section in the README: https://github.com/lvillani/android-cropimage#gradle-repository

Admittedly, if you follow these instructions by the letter, you will get an older version of the library. I'm updating the Gradle dependency directive to reference version 1.1.0.

**Comment by BatDroid** [comment]
well thanks to you the outline color now works fine when i changed to version 1.1.0,
but the minsdk(API) is still 15, would you please change that line to 14 ?

**Comment by lvillani** [comment]
The API level issue has been discussed here: https://github.com/lvillani/android-cropimage/issues/31.

I'm closing this ticket since the original issue has been fixed.
