### ISSUE TITLE
Resize without maintaining the proportion

### ISSUE THREAD

**Issue by barbosa-renan** [lvillani/android-cropimage#39]
How do I resize without maintaining the proportion? I need to crop the image so that it is in rectangular shape.

**Comment by lvillani** [comment]
Use [this constructor](https://github.com/lvillani/android-cropimage/blob/142f81357120d7f0c77cac21edda8daf3701b960/CropImage/src/main/java/com/android/camera/CropImageIntentBuilder.java#L103) passing zero to both aspectX and aspectY.
