### ISSUE TITLE
Bug on Samsung Galaxy A5

### ISSUE THREAD

**Issue by barbosa-renan** [lvillani/android-cropimage#41]
In some tests, the application installed on a Samsung A5. To go to the image cropping rectangle and cut the overall background is filled with gray. The same version was installed on Motorola Moto E and a Sansung Galaxy S2, running smoothly.
![img-20150430-wa0002](https://cloud.githubusercontent.com/assets/8302766/7453933/b891efee-f244-11e4-87dc-2c9ca10641f1.jpg)

**Comment by lvillani** [comment]
That's weird. As you say `android-cropimage` works fine on two other devices. Unfortunately, without access to the hardware there isn't much I can do to fix or work-around the issue. I would gladly accept a patch if you find a fix for this problem, though.

**Comment by barbosa-renan** [comment]
I checked all the code and did not find a solution, I am trying to solve this problem and post a patch as soon as you can.

**Comment by barbosa-renan** [comment]
The problem wasn't related to the rectangle and filled out. In fact the mImageView wasn't being loaded with the Bitmap, the solution was to change [this line](https://github.com/lvillani/android-cropimage/blob/142f81357120d7f0c77cac21edda8daf3701b960/CropImage/src/main/java/com/android/camera/CropImage.java#L110) increasing the range of the SDK. The Samsung Galaxy A5 is at version 19, to change the range to support this version, everything worked normally, including in other devices in which I had already tested. Problem solved.

```
if (Build.VERSION.SDK_INT > 10 && Build.VERSION.SDK_INT < 20) { // >= Gingerbread && < Kit kat
            mImageView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
        }
```
