### ISSUE TITLE
Gradle install error

### ISSUE THREAD

**Issue by Zeyad-37** [lvillani/android-cropimage#47]
Error:(49, 13) Failed to resolve: me.villani.lorenzo.android:android-cropimage:1.1.0
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by lvillani** [comment]
What's your Gradle configuration? Did you follow instructions from the README file?

**Comment by Zeyad-37** [comment]
I forgot to add the maven url sorry
