### ISSUE TITLE
crop activity always rotating image

### ISSUE THREAD

**Issue by huyhu** [lvillani/android-cropimage#48]
In Samsung Galaxy S3 and LG G3, the image is automatically rotated 90degrees while original image is not rotated. But it's working fine in Nexus 5. Is there any possible solution for it?

**Comment by lvillani** [comment]
How are you taking the photos? Portrait or landscape? Can you check that the camera application doesn't insert EXIF rotation tags in the picture? (Or, if it does, that they are actually correct).

**Comment by huyhu** [comment]
Hi Lorenzo, thanks for reply.
im taking pictures portrait and they are turning in landscape. if i take picture landscape they are turning portrait. So it can be about EXIF rotation and what else? do you have other opinions?

**Comment by lvillani** [comment]
Can you send me a sample picture shot in landscape and another one shot in portrait?

**Comment by huyhu** [comment]
Hi Lorenzo,
i believe it's not related with your library. Thanks.
