### ISSUE TITLE
java.lang.RuntimeException: Failure delivering result ResultInfo

### ISSUE THREAD

**Issue by gokberkyagci** [lvillani/android-cropimage#49]
Can you help me about this problem ?
http://stackoverflow.com/questions/31941479/java-lang-runtimeexception-failure-delivering-result-resultinfo

**Comment by lvillani** [comment]
The stacktrace shows an NPE in `onActivityResult()` but it doesn't show which line is throwing it. I suggest using the debugger.

**Comment by lvillani** [comment]
I'm assuming this is a problem outside the realm of android-cropimage and closing this issue. Feel free to re-open if necessary.
