### ISSUE TITLE
cropimage lib not working on some devices

### ISSUE THREAD

**Issue by alirezasaremi** [lvillani/android-cropimage#51]
This is a great cropping image lib but it's not working on some devices. I've test it on Samsung galaxy tab 10 2.1 and work great but not working on HUAWEI y221 and log cat has no error.
any solution would help me. 
thank you

**Comment by lvillani** [comment]
Do you have any additional information to provide? I don't have any Huawei device to test on and without a stack trace I'm afraid I won't be able to work on a fix.

**Comment by lvillani** [comment]
I'm closing this issue due to the lack of further information to proceed with a fix. Feel free to re-open if you have more information.
