### ISSUE TITLE
Only square crop is possible, user is not able to crop it in rectangle shape

### ISSUE THREAD

**Issue by ShreyashPromact** [lvillani/android-cropimage#56]
I have use this library to crop image. I have try a lot but I am not able to crop the Image in rectangle shape.
I am wonder if it is possible to do with this library or not.
Please let me know if it is possible to do with this library.

Sincerely,
Shreyash

**Comment by Mahdiazadbar** [comment]
I dont know this library work or not. I cant remember test it. But i use this library. This work very good
https://github.com/jdamcd/android-crop

**Comment by ShreyashPromact** [comment]
@Mahdiazadbar 
Thanks for link. I have already checked it. But the problem is, I want to have rectangle crop also. while this library and the one you give me in comment are not supported to crop rectangle. 

Let me know if you have any other library in mind that cropped in rectangle shape as well.

Sincerely,
Shreyash

**Comment by Mahdiazadbar** [comment]
You can see this link for croping in rectangle mode
https://github.com/jdamcd/android-crop/pull/71

**Comment by lvillani** [comment]
My guess is that by playing with aspect ratios you should be able to crop rectangles instead of squares.

**Comment by ShreyashPromact** [comment]
@Mahdiazadbar 
I have seen that link. But not getting proper idea with how to make it possible. I want to have it like adjustable rectangle crop. I am not sure it is possible or not with that.

@lvillani 
You are right, But I want to have it on the touch listener. Something like, user can adjust the rectangle or square shape as per his interest and crop it.

Sincerely,
Shreyash

**Comment by Mahdiazadbar** [comment]
I dont know. But i use it. And work

Sent from Yahoo Mail on Android 
 
  On Mon, 4 Jan, 2016 at 14:54, Shreyash Mahajan<notifications@github.com> wrote:   
@Mahdiazadbar 
I have seen that link. But not getting proper idea with how to make it possible. I want to have it like adjustable rectangle crop. I am not sure it is possible or not with that.

@lvillani 
You are right, But I want to have it on the touch listener. Something like, user can adjust the rectangle or square shape as per his interest and crop it.

Sincerely,
Shreyash

**Comment by lvillani** [comment]
@ShreyashPromact If jdamcd/android-crop does what you need I strongly suggest you to switch to that library.

This library is just a re-packaging of code found on AOSP and I mean for it to stay as close as possible to upstream. This project should be used as-is or as a base for a more complete package. jdamcd/android-crop is based on my work but seems to extend it meaningfully and provides a modern user interface.

I'm closing this issue since doing what you need involves changes to the code base that I would rather avoid for the reasons I stated above.

**Comment by ShreyashPromact** [comment]
@lvillani 

I have raised this issue here, because normally user wants to have freedom to crop image from any shape (square/rectangle). So that should be cover with in that library. Otherwise there are other library which gives same (or even more) then this library have.

Anyway, Its upto you whether you take it as seriously or just leave it. I suggest you to keep this issue open and remain it as it is uptill you update it with mention functionality.

Thanks for your reply.

Sincerely,
Shreyash

**Comment by ShreyashPromact** [comment]
@lvillani 
I have just check that library in more proper way.
That library is not giving facility to user to change the shape at runtime. That has to be as per the user selection.

I have check one library called [cropper.](https://github.com/edmodo/cropper) which gives that flexibility to crop the image in different way as user want. But there is drawback of that library, that the Image quality is not proper after cropping and also it gives small Image view to crop it.


Sincerely,
Shreyash

**Comment by prpatel** [comment]
In case someone lands here wondering how to do this, you simply have to pass 0 as the aspectX and aspectY params and it will allow the user to to touch each edge and change the selection for just that edge.

**Comment by lvillani** [comment]
Thanks for finding that out, @prpatel 👍

**Comment by ShreyashPromact** [comment]
@prpatel 
In that case, Please pull the code and commit your changes. So that all get the things working as expected to.

Sincerely,
Shreyash

**Comment by prpatel** [comment]
@ShreyashPromact There is nothing to commit. Simply use the intent builder like so:
CropImageIntentBuilder intentBuilder = new CropImageIntentBuilder(0, 0, outputX, outputY, destFileUri);

**Comment by ShreyashPromact** [comment]
Seems like, It will work. I will try it later. Thanks for reply.

Sincerely,
Shreyash
