### ISSUE TITLE
libpng warning: iCCP

### ISSUE THREAD

**Issue by DevenSingh27** [lvillani/android-cropimage#60]
AAPT err: me.villani.lorenzo.android\android-cropimage\1.1.0\res\drawable-mdpi-v4\detail_photo_border.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

**Comment by lvillani** [comment]
Can you provide more information such as os, platform tools version, target api level, etc?

**Comment by lvillani** [comment]
No information provided by reporter. Closing.
